language: java
before_install:
  - echo "------------------"
  - sudo echo "JAVA_HOME = $JAVA_HOME"
  - sudo ls -alF $(dirname "$JAVA_HOME")
  - sudo ls -alF "$JAVA_HOME"
  - sudo ls -alF "$JAVA_HOME"/bin
  - echo "------------------"
script:
  - mvn package
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
  - openjdk7