language: java
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mpack
script:
  - mvn package
after_success:
  - src/main/scripts/package-send.sh
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
