language: java
before_script:
  - echo "------------------"
  - echo "JAVA_HOME: $JAVA_HOME"
  - ls -alF $JAVA_HOME
  - echo "------------------"
script:
  - mvn package
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7