language: java
before_script:
  - echo "------------------"
  - sudo echo "JAVA_HOME = $JAVA_HOME"
  - sudo ls -alF "$JAVA_HOME"
  - echo "------------------"
script:
  - mvn package
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7